### ISSUE TITLE
Shiny App Collaboration: Social Spatial Polarization

### ISSUE THREAD

**Issue by Lfrueh** [Drexel-UHC/analytics-corner#20]
### Name

Lisa Frueh

### Job title

PhD Student

### Department

Environmental and Occupational Health Department

### Request type

Code review / collaboration

### Output

Technical consultation

### Request description

I’ve been working on a Shiny App to build an interactive, GIS-based resource for displaying ICE measures (a measure of racial/ethnic segregation). I made a lot of progress on my own but have stalled as I can’t get the performance smoother, and for any spatial scales smaller than a county area, the app crashes online. Steve suggested I reach out to you for some troubleshooting advice. I know this is a busy time of year, but is there a time in the next few months where you might be able to look through my code or sit down with me and look through it together? Right now I’m looking to improve performance enough to make it worth paying to host the app online (since the free version of shinyapps.io can’t seem to handle this size).
 

### Example

[Current version of the app](https://lisa-frueh.shinyapps.io/ssp_maps/)

[Data repository Github](https://github.com/samjaros-stanford/spatial_social_polarization_database)

### Data

Data is publicly available ACS data.

### Notes

I'm relatively new to collaborating on Github, so I might need a little advice on how to merge changes back into the 'main' branch.

**Comment by ran-codes** [comment]
This looks great @Lfrueh 👍 . Will take a look and give updates next Friday!

Thanks,
Ran

**Comment by ran-codes** [comment]
@Lfrueh let me know how the deployment works (#21). If the production version on the UHC ShinyAppsio is working okay, please feel free to close this issue.

Again ... your app looks great haha. way ahead of when I was a grad student. 😄
