### ISSUE TITLE
GitHub/R Skills Workshop Session 2

### ISSUE THREAD

**Issue by hal-ch** [Drexel-UHC/analytics-corner#22]
### Name

Hal Chen

### Job title

Doctoral Fellow

### Department

Epidemiology and Biostatistics Department

### Request type

Technical training

### Output

Training

### Request description

Following up on the first skills workshop, we'd like a more in-depth follow-along demonstration of using R/GitHub in a reproducible workflow. Your suggestion of having Ana Lucia and Diana demonstrate sounds like a good idea! I think it would be helpful to either have participants install GitHub Home beforehand or have live instruction on doing so. Ran's GitHub workshop at UHC was very helpful and I think something in that format would be ideal.

**Comment by ran-codes** [comment]
Thanks @hal-ch for the reminder. Very excited to see this moving forward . Feel free to drop when ever you are at UHC to discuss this. 

@dianahiguera @AnaPeraltaG lets find some time to chat about this! I'll send out an email.
