### ISSUE TITLE
Help with grant

### ISSUE THREAD

**Issue by lesliemcclure** [Drexel-UHC/analytics-corner#3]
## Request  
- Type: Help with grant
- Example:
- Data:
- Notes:  I am working with Ana Diez Roux and Jane Clougherty to write a grant proposing that we at Drexel be the Research Coordinating Center for a Climate Change and Health Community of Practice. The grant would provide funding to do many of the things that folks at the UHC are doing for SALURBAL, including providing "high-security-compliant, high-capacity informatics infrastructure suitable for data integration, storage, management, and sharing and ensure that the data meet the FAIR principles: findability, accessibility, interoperability, and reusability." While we are doing this for several projects across our groups, I am having a hard time describing the first part (high-security-compliant, high-capacity informatics infrastructure suitable for data integration, storage, management, and sharing). Ana suggested I reach out to you to see if you could help us draft some language that describes how we do this?

Happy to take a few minutes to chat about this if you'd like, or if you have suggestions of others to reach out to, I'd appreciate that.

**Comment by rl627** [comment]
Thanks so much for submitting the first ticket 🥇! I just have a few quick follow-up questions:

- How long of a description (# of words) are you looking for?
- What is the timeline for getting this draft?

**Comment by rl627** [comment]
> To be honest, we can edit down whatever text you give us! Timeline - I believe we are hoping to finalize the text by the end of next week.

Okay. Will have something for you by end of the week. 

> I understand that you, Jody, and Nora are meeting Friday morning, and I am going to try to attend that as well!

Looking forward to connecting 😄!

**Comment by rl627** [comment]
Thanks for the patience. There are two things here (which have both been forwarded to Ana via email.... waiting for her to get a GitHub in the future 🙏)
- [grant infrastructure slides.pptx](https://github.com/Drexel-UHC/analytics-core/files/9284279/grant.infrastructure.slides.pptx) which are the slides from our meeting on 8/5/22
- [grant infrastructure language.docx](https://github.com/Drexel-UHC/analytics-core/files/9284277/grant.infrastructure.language.docx) just contains some drafted language that talks about informatics infrastructure within the context of our experience with Covid projects and SALURBAL.
